trigger:
  - master

pool:
  name: Default

steps:
  - script: echo Hello,it's my Azure Devops App
    displayName: 'Run an echo command'

  - script: mvn cleam install
    displayName: 'Buid with maven'

  - script: java -jar target/maven1-0.0.1-SNAPSHOT.jar
    displayName: 'Run a JAR file'